"""empty message

Revision ID: d5999f0f2928
Revises: b23c6211a62f
Create Date: 2019-12-03 21:01:40.983838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5999f0f2928'
down_revision = 'b23c6211a62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_blog', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_blog'], ['blog_models.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect_models')
    # ### end Alembic commands ###
